# Environment Config
lnc.config.serverType=local
lnc.config.os=windows
lnc.config.database=oracle
lnc.config.database.version=10g
lnc.config.database.charset=utf-8
lnc.config.was=
lnc.config.was.version=
lnc.config.lang=utf-8
lnc.config.debug=
lnc.config.han.encoding=
lnc.config.projectname=
lnc.config.session=
lnc.config.cookie.time=
lnc.config.cookie.domain=
lnc.config.index.fullurl=

lnc.config.ssl.use.yn=N

#jdbc/LncDB
lnc.jndi.name=

#site languageset 
lnc.config.languageset=kr|us


# Url / Filepath Setting
lnc.server.url=
lnc.server.subpath=
#lnc.server.contextroot=/home/App/EduDesk
lnc.server.contextroot=C:/00_crepas/01_workspace/wtpwebapps/EduDesk/EduDesk

lnc.server.domain=
lnc.server.port=
lnc.server.wasport=

lnc.rootpath.user=/user
lnc.rootpath.webinf=/WEB-INF
lnc.rootpath.admin=/admin


#referer Check Url (ex: /user/boardList.action,/user/boardWriteExecute.action)
#referer.check.url=/user/boardList.action,/user/boardWriteExecute.action,/user/albumWriteExecute.action,/user/movieWriteExecute.action

#File Upload disabled extension
#jsp|exe|sh|php|asp|aspx|js|css|html|class|rpm|vm|java|java
lnc.file.upload.disabled.extension=jsp|exe|sh|php|asp|aspx|js|class|rpm|vm|java

#default upload filesize 50 : 50MB
lnc.upload.max.fileSize=50

#board upload default fileType
lnc.board.upload.default.fileType=alz,zip,txt,hwp,xls,xlsx,ppt,pptx,doc,docx,jpg,gif,bmp,asf,wma,avi,mpg,wmv,mpeg,pdf
lnc.album.upload.default.fileType=jpg,gif,png
lnc.movie.upload.default.fileType=asf,wma,avi,mpg,wmv,mpeg,jpg,gif,png

#image file size limit : 2 (MB)
lnc.image.upload.default.fileSize=


# \uc18c\uc2a4 \uad00\ub9ac\uc790\uc778\uc9c0 \uc0ac\uc6a9\uc790 \uc778\uc9c0 \uad6c\ubd84
# \uad00\ub9ac\uc790 : manager
# \uc0ac\uc6a9\uc790 : user
lnc.source.type=manager

###################################################################################
###################################################################################
#smtp mail info
mail.smtp.host=smtps.hiworks.com
mail.smtp.port=465
mail.smtp.sslYn=Y
mail.smtp.encode=utf-8
mail.smtp.debug=Y
mail.smtp.from=kbj@koons.co.kr
mail.smtp.id= kbj@koons.co.kr
mail.smtp.pw=koons123$%
###################################################################################
###################################################################################

#\uc694\uae08\ud560\uc778\uc870\ud68c IP, PORT
discount.server.ip=192.168.101.187
discount.server.port=47171

lnc.smartcheck.url=http://localhost:8180




