domain.name=http://localhost:8580
service.name=\uc7ac\uc815\uacbd\uc81c\ubd80 \uc735\ubcf5\ud569\uacbd\uc81c\uc7ac\uc815\uad50\uc721\ud50c\ub7ab\ud3fc
lnc.app.contextpath=

# Url / Filepath Setting
lnc.server.url=
lnc.server.subpath=
lnc.server.contextroot=/CSIA/apache-tomcat-8.5.72/webapps/ROOT
lnc.server.tmproot=/MOEF/tmp/
lnc.server.dataroot=/MOEF/data/

lnc.server.domain=
lnc.server.port=
lnc.server.wasport=

lnc.rootpath.user=/user
lnc.rootpath.webinf=/WEB-INF
lnc.rootpath.admin=/admin

lnc.file.upload.disabled.extension=jsp|exe|sh|php|asp|aspx|js|class|rpm|vm|java

#default upload filesize 50 : 50MB
lnc.upload.max.fileSize=50

#board upload default fileType
lnc.board.upload.default.fileType=alz,zip,txt,hwp,xls,xlsx,ppt,pptx,doc,docx,jpg,gif,bmp,asf,wma,avi,mpg,wmv,mpeg,pdf
lnc.album.upload.default.fileType=jpg,gif,png
lnc.movie.upload.default.fileType=asf,wma,avi,mpg,wmv,mpeg,jpg,gif,png

#image file size limit : 2 (MB)
lnc.image.upload.default.fileSize=


# \uc18c\uc2a4 \uad00\ub9ac\uc790\uc778\uc9c0 \uc0ac\uc6a9\uc790 \uc778\uc9c0 \uad6c\ubd84
# \uad00\ub9ac\uc790 : manager
# \uc0ac\uc6a9\uc790 : user
lnc.source.type=manager

###################################################################################
###################################################################################
#smtp mail info
mail.smtp.host=27.101.208.78
mail.smtp.port=25
mail.smtp.sslYn=N
mail.smtp.encode=utf-8
mail.smtp.debug=Y
mail.smtp.from=ceef@korea.kr
mail.smtp.id=
mail.smtp.pw=
###################################################################################
###################################################################################

#\uc694\uae08\ud560\uc778\uc870\ud68c IP, PORT
discount.server.ip=192.168.101.187
discount.server.port=47171

lnc.smartcheck.url=http://localhost:8180

#\ud074\ub77c\uc6b0\ub4dc  cdn
#cloud.cdn.url=https://kr.object.gov-ncloudstorage.com/edu-dev
cloud.cdn.url=/DATA
cloud.storage.bucket=edu-dev
#cloud.server2.url=http://localhost:8080
cloud.server2.url=http://localhost:8580

#\uacb0\uc81c\ubaa8\ub4c8
pay.easypay.mallId=T0012140
pay.easypay.encKey=easypay!KICCTEST
pay.easypay.returnUrl=http://192.168.0.164:8080/edu/user/pay/easypay/res.do
pay.easypay.receiptUrl=http://testoffice.easypay.co.kr/receipt/ReceiptBranch.jsp
pay.easypay.webpayUrl=https://testpgapi.easypay.co.kr/api/trades/webpay
pay.easypay.approvalUrl=https://testpgapi.easypay.co.kr/api/trades/approval
pay.easypay.retrieveTransactioUrl=https://testpgapi.easypay.co.kr/api/trades/retrieveTransactio
pay.easypay.reviseUrl=https://testpgapi.easypay.co.kr/api/trades/revise

pay.toss.clientKey=test_ck_ALnQvDd2VJ655JwywzDaVMj7X41m
pay.toss.secretKey=test_sk_DpexMgkW36wwlPGWwzR4VGbR5ozO
#pay.toss.clientKey=live_ck_QbgMGZzorz5Ljnj6Q0Y7Vl5E1em4
#pay.toss.secretKey=live_sk_Ba5PzR0ArnwDX5NA2MGG8vmYnNeD

#nicecheck
nice.check.siteCd=CH002
nice.check.sitePw=4Nn6WTSrcRep

#niceipin
nice.ipin.siteCd=A093
nice.ipin.sitePw=50381108
