##### SP \uc124\uc815 ########################
#Wallet \ud30c\uc77c \uc138\ud305 - IDE \uac1c\ubc1c\uc6a9
app.sp-keymanager-path= classpath:config/moef_lms.wallet

#SP DID \ud30c\uc77c \uacbd\ub85c - IDE \uac1c\ubc1c\uc6a9
app.sp-did-path= classpath:config/moef_server_api.did

#Wallet password
app.sp-keymanager-password=moef_lms

#key id
app.sp-main-key-id=moefkey

#SP \ube14\ub85d\uccb4\uc778 \uacc4\uc815 
app.sp-account= sp.cnvrg

#SP Service Code
app.sp-service-code= srv.cnvrg

#\ube14\ub85d\uccb4\uc778\uc744 \ud1b5\ud55c \uac80\uc99d, true = \uc2a4\ub9c8\ud2b8\ucee8\ud2b8\ub799\ud2b8\ub97c \ud1b5\ud55c \uac80\uc99d, false = \ub85c\uceec \uc11c\ubc84\uc5d0 \uac80\uc99d 
app.verify-check-blockchain=false
######################################


##### SDK \uc138\ud305  #######################
#\uc0c1\uc138 \ub85c\uadf8 \uc0ac\uc6a9 \uc5ec\ubd80 
app.sdk-detail-log= true

#\ube14\ub85d\uccb4\uc778 \uc870\ud68c \uce90\uc2f1 \uc0ac\uc6a9 \uc5ec\ubd80 
app.sdk-use-cache= false
######################################


##### \uc11c\ubc84 \uc138\ud305  #######################
#Blockchain (\uc778\ud130\ub137\ub9dd - \ud14c\uc2a4\ud2b8\uc6a9)
#app.blockchain-server-domain   = http://27.101.219.178:18888
#Blockchain (\uc778\ud130\ub137\ub9dd - \uc6b4\uc601\uc6a9)
#app.blockchain-server-domain   = https://bc.id.go.kr:18888
#Blockchain (\uc5c5\ubb34\ub9dd - \ud14c\uc2a4\ud2b8\uc6a9)
app.blockchain-server-domain   = http://27.101.219.178:18888
#Blockchain (\uc5c5\ubb34\ub9dd - \uc6b4\uc601\uc6a9)
#app.blockchain-server-domain   = http://10.175.91.208:18888

#Callback (\uc778\ud130\ub137\ub9dd - \ud14c\uc2a4\ud2b8/\uc6b4\uc601\uc6a9 \uc608\uc2dc)
#app.blockchain-callback        = http://192.168.106.22:8080/demo/spnoneprofile/verify
#Callback (\uc5c5\ubb34\ub9dd - \ud14c\uc2a4\ud2b8\uc6a9 \uc608\uc2dc)
app.blockchain-callback        = http://106.244.74.221:28080/spnoneprofile/verify.do
#Callback (\uc5c5\ubb34\ub9dd - \uc6b4\uc601\uc6a9 \uc608\uc2dc)
#app.blockchain-callback        = https://id.go.kr:1443/omniproxy/bysp?hname={{\ubaa8\ubc14\uc77c\uacf5\ubb34\uc6d0\uc99d \uc6b4\uc601\uc0ac\uc5c5\ub2e8\uc5d0\uc11c \uc548\ub0b4\ud55c hname}}
######################################